//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LicensePlatesDBFirst.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GamePlate
    {
        public GamePlate()
        {
        }

        public GamePlate(int gameId, int plateId)
        {
            GameId = gameId;
            PlateId = plateId;
        }
        public int Id { get; set; }
        public Nullable<int> GameId { get; set; }
        public Nullable<int> PlateId { get; set; }
    
        public virtual Game Game { get; set; }
        public virtual Plate Plate { get; set; }
    }
}
